### ISSUE TITLE
Computer freezing

### ISSUE THREAD

**Issue by Zapotel** [GetDotaStats/GetDotaLobby#16]
After host lobby start the map my computer is freezing and i can't do anything, ctrl+alt+del, alt+tab or something is doesn't helping, only emergency switching off. Help me with this problem pls.

**Comment by jimmydorry** [comment]
You need to wait. It can take a minute or two for Source2 to start. It may be possible that your computer is simply not strong enough to handle Source2. Could you start games in the past?

The whole issue may not be worth your trouble trying to fix, as the Dota2 Beta will be released shortly.

**Comment by Zapotel** [comment]
I've played maps earlier but now... this disaster.

**Comment by Zapotel** [comment]
Yes, i know about dota 2 reborn, it's will be awesome

**Comment by jimmydorry** [comment]
No followup
