### ISSUE TITLE
'textField' in all areas

### ISSUE THREAD

**Issue by JFulweber** [GetDotaStats/GetDotaLobby#2]
For the map and gamemode drop down menu in the lobby viewer and host menu, 'textField' is the only thing that comes up. I'm guessing it's the reason that I can't see any active lobbies, as well.

**Comment by jimmydorry** [comment]
Is this still an issue? We have since deployed two updates targeted at fixing this issue, which occurs due to latency.

**Comment by JFulweber** [comment]
Nope, everything is all good, sorry for not closing this issue. I didn't anticipate you being so active in the chatbox, good on you for participating and being helpful.

**Comment by jimmydorry** [comment]
No problems, glad it's working for you.
