### ISSUE TITLE
broken translation strings in client

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/GetDotaLobby#4]
https://github.com/GetDotaStats/site/issues/103

Reported by @domovoi0ng

**Comment by jimmydorry** [comment]
I don't believe that should happen, but BMD would know. Can you try verifying your game cache?

**Comment by bmddota** [comment]
The Lobby Explorer and minigames don't directly impact (and barely use) the built-in translation/localization system, so I'm not sure how this could happen.  Those strings are listed in the resources/dota_english.txt (or dota_language.txt) file which we don't mess with, and should be kept up to date by Steam itself.  Verifying your cache would be the best move here.

**Comment by Domovoi0ng** [comment]
verifying the game cache fixed it, apparently only one file was missing and
the download was of 0kb.  According to my snooping aroud i reckon
options.kv was the missing file.  Thanks for your help and sorry for the
trouble!
