### ISSUE TITLE
LXUpdater not updating (probably caused by decimal format for local language)

### ISSUE THREAD

**Issue by chocolateftw** [GetDotaStats/GetDotaLobby#6]
I am using Windows 7 64bit with the language set to german.

If I try to update I get this screen:
![snip](https://cloud.githubusercontent.com/assets/11755646/6943429/3dd8f20e-d88e-11e4-8793-cf7bd25da745.png)

The file %APPDATA%\version.txt contains the text: 0**,**33
Notice the comma which is the decimal mark in german.
The client seems to convert this text to 33 or 033. (on reading the file)
Changing the text in %APPDATA%\version.txt to 0**.**33 (with a point) fixes the issue. The LXUpdater reads and show the client version correctly and starts updating.

The problem seems to be at the moment when the LXUpdater saves the version number 0**.**33 to the %APPDATA%\version.txt
Maybe Visual Basic saves numbers using the decimal mark for the local language.

**Comment by bmddota** [comment]
chocolateftw, thanks for the report.  We noticed this issue as well and updated the LXUpdater.vbs to handle it.  Unfortunately, the updater provides no udpater for itself, so you'll need to download the fixed version at https://github.com/GetDotaStats/GetDotaLobby/raw/master/LXUpdater.zip .

Additionally, you should delete %APPDATA%\version.txt before running the new version as it will likely still goof up.  Apologies for the issue.

**Comment by chocolateftw** [comment]
Thank you for your quick response!
Edit: The bug seems to still exist. (Even though I deleted the version.txt and redownloaded the updater)
Edit2: Clarification. It will update once, but then again has the version number with a comma in the version.txt and reads that number wrong when i rerun the updater.

**Comment by chocolateftw** [comment]
Fixed by http://git.io/vefFX
