### ISSUE TITLE
No plus window / NeedHelp

### ISSUE THREAD

**Issue by RomeoChicken** [GetDotaStats/GetDotaLobby#8]
Hi ive got a problem. When a lobby starts i fail i mean no other window is opening its just staying in main dota window then i can reconnect over and over again and nothing... Help? 2 weeks ago it worked but now since ive reinstalled dota it won`t work...

**Comment by jimmydorry** [comment]
Do you have a wanky steam name? Source2 doesn't work with some characters.

Can you copy paste a log from both the computer icon at the top, and dota console?

**Comment by RomeoChicken** [comment]
This is my name it worked at the first time   ΔilimatiΔ

**Comment by jimmydorry** [comment]
Try it without the weird characters.

**Comment by RomeoChicken** [comment]
Can u explain to me?  Like you would explain to a noob
Ok i did

**Comment by jimmydorry** [comment]
http://i.imgur.com/FKcfHsv.png

http://i.imgur.com/UO6UBNF.png

Change your name to something simple and see if that works.

**Comment by RomeoChicken** [comment]
Okay  i`ve done that

**Comment by RomeoChicken** [comment]
Let me try

**Comment by jimmydorry** [comment]
Did you try playing a game? Make your own lobby and do it with just yourself.

![HeadFace](http://dota2.photography/images/misc/lx/meme/FailFish.png)

**Comment by RomeoChicken** [comment]
Ok, wait a min

**Comment by RomeoChicken** [comment]
When i try to make a lobby  it says  dota 2 work shop tools required     I installed both of them

**Comment by jimmydorry** [comment]
Follow the full guide half way down the page http://getdotastats.com/#d2mods__lobby_guide

**Comment by RomeoChicken** [comment]
I did...

**Comment by jimmydorry** [comment]
Including the DLC on Dota2? I haven't seen this issue from any other user. You must have missed a step.

**Comment by RomeoChicken** [comment]
I`ll make some screens to show you.

**Comment by RomeoChicken** [comment]
http://imgur.com/YClQZLy,4lJfdxU,u7yHxKK,5ABTeMf

**Comment by jimmydorry** [comment]
Have you tried launching the tools by themselves? They have pre-reqs like directX, etc.

**Comment by RomeoChicken** [comment]
Um... Not really  i`ll try it. But not now... Bcs i have to go 
How can i contact you? Or should i just write here and wait for u to replay?

**Comment by jimmydorry** [comment]
The IRC channel is the best place, follow by github.

http://kiwiirc.com/client/irc.gamesurge.net/?#getdotastats

**Comment by jimmydorry** [comment]
Closing this issue due to in-activity. With the supplied information, it can't be related to the Lobby Explorer. Drop by the IRC channel if you need further help.
